namespace MGBreakCaptcha2.ColorML
{
    public static class ColorData
    {
        public static double[][] Data =
        {
            new double[] {255, 58, 147},
            new double[] {255, 58, 147},
            new double[] {255, 51, 153},
            new double[] {255, 51, 255},
            new double[] {199, 21, 133},
            new double[] {155, 48, 255},
            new double[] {255, 110, 180},
            new double[] {147, 112, 219},
            new double[] {255, 105, 180},
            new double[] {255, 110, 180},
            new double[] {255, 58, 147},
            new double[] {46, 139, 87},
            new double[] {34, 139, 34},
            new double[] {60, 179, 113},
            new double[] {46, 193, 87},
            new double[] {0, 139, 0},
            new double[] {46, 139, 87},
            new double[] {34, 139, 34},
            new double[] {107, 142, 35},
            new double[] {50, 205, 50},
            new double[] {50, 205, 50},
            new double[] {0, 139, 0},
            new double[] {0, 139, 0},
            new double[] {153, 0, 204},
            new double[] {138, 43, 226},
            new double[] {160, 32, 240},
            new double[] {147, 112, 219},
            new double[] {160, 32, 240},
            new double[] {155, 48, 255},
            new double[] {155, 48, 255},
            new double[] {160, 32, 240},
            new double[] {138, 43, 226},
            new double[] {153, 0, 204},
            new double[] {147, 112, 219},
            new double[] {255, 140, 0},
            new double[] {255, 113, 51},
            new double[] {255, 165, 0},
            new double[] {238, 154, 0},
            new double[] {238, 154, 0},
            new double[] {255, 165, 0},
            new double[] {255, 102, 0},
            new double[] {255, 113, 51},
            new double[] {238, 154, 0},
            new double[] {255, 140, 0},
            new double[] {255, 10, 15},
            new double[] {216, 32, 32},
            new double[] {216, 32, 32},
            new double[] {255, 48, 48},
            new double[] {255, 10, 10},
            new double[] {255, 0, 0},
            new double[] {238, 44, 44},
            new double[] {216, 32, 32},
            new double[] {255, 10, 15},
            new double[] {255, 69, 0},
            new double[] {0, 0, 128},
            new double[] {0, 178, 238},
            new double[] {0, 0, 128},
            new double[] {0, 0, 255},
            new double[] {0, 0, 255},
            new double[] {24, 116, 205},
            new double[] {50, 50, 50},
            new double[] {40, 40, 40},
            new double[] {25, 25, 25},
            new double[] {38, 38, 35},
            new double[] {0, 0, 0}
        };

        public static int[] Label =
        {
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Rosa.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Verde.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Roxo.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Laranja.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Vermelho.GetHashCode(),
            ColorsEnum.Azul.GetHashCode(),
            ColorsEnum.Azul.GetHashCode(),
            ColorsEnum.Azul.GetHashCode(),
            ColorsEnum.Azul.GetHashCode(),
            ColorsEnum.Azul.GetHashCode(),
            ColorsEnum.Azul.GetHashCode(),
            ColorsEnum.Preto.GetHashCode(),
            ColorsEnum.Preto.GetHashCode(),
            ColorsEnum.Preto.GetHashCode(),
            ColorsEnum.Preto.GetHashCode(),
            ColorsEnum.Preto.GetHashCode()
        };
    }
}